language: android
jdk: oraclejdk7

branches:
  only:
    - develop
    
env:
  matrix:
    - ANDROID_TARGET=android-19

android:
  components:
    - build-tools-19.1.0
    - android-19                 
    - extra-android-support
    
licenses:
    - android-sdk-license-5be876d5

before_install:
    - chmod +x gradlew
