language: android
jdk: oraclejdk7

branches:
  only:
    - develop
    
env:
  matrix:
    - ANDROID_TARGET=android-20

android:
  components:
    - build-tools-19.1.0
    - android-20                    
    - extra-android-support

before_install:
    - chmod +x gradlew
